### PR TITLE
A number of fixes and tweaks

### PR DESCRIPTION
**Pull request by kevmoo**
Thoughts?

### CODE REVIEW

**Comment by kevmoo** [comment]
@cbracken Ping?

**Comment by kevmoo** [comment]
@cbracken Chris?

**Comment by kevmoo** [comment]
@cbracken it's wonderful. It'll make you smile. :smile:

**Comment by kevmoo** [comment]
@cbracken Once this is green on Travis, we should be good to go.

I'm not running tests on Travis dev, per https://github.com/dart-lang/coverage/issues/70

**Comment by kevmoo** [comment]
@cbracken :goat:

**Comment by cbracken** [comment]
#70 is fixed. Starting on this as I write this. Will likely yank these in piecewise.

**Comment by cbracken** [comment]
Merged as... a whole lotta SHAs. Thank you monsieur!

**Pull request closed without merging**
