### PR TITLE
Migrate collect_coverage to async-await.

### PR DESCRIPTION
**Pull request by cbracken**
Addresses #75 for collect_coverage.dart.

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/coverage/78)

### CODE REVIEW

**Comment by kevmoo** [comment]
See comments

---

Review status: 0 of 1 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[bin/collect_coverage.dart, line 33 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/78#-Jpx3vmfSu-uem0e117Q)** ([raw file](https://github.com/dart-lang/coverage/blob/3719fbddadb07beac2529f0ceb4150d503475ee0/bin/collect_coverage.dart#L33)):</sup>
Since this is an async function, you could just do

`if (!paused) throw "Not all of the isolates are paused."`

---

<sup>**[bin/collect_coverage.dart, line 55 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/78#-Jpx4IuhmekKND7aOQZc)** ([raw file](https://github.com/dart-lang/coverage/blob/3719fbddadb07beac2529f0ceb4150d503475ee0/bin/collect_coverage.dart#L55)):</sup>
You have to reassign `connected = connected.timeout...`

Otherwise you're waiting on the original future, not the timeout version

---

<sup>**[bin/collect_coverage.dart, line 70 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/78#-Jpx4hColgOBtmXubtnJ)** ([raw file](https://github.com/dart-lang/coverage/blob/3719fbddadb07beac2529f0ceb4150d503475ee0/bin/collect_coverage.dart#L70)):</sup>
await here!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/78)

**Comment by kevmoo** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- bin/collect_coverage.dart @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/78)

**Comment by cbracken** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[bin/collect_coverage.dart, line 33 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/78#-Jpx3vmfSu-uem0e117Q)** ([raw file](https://github.com/dart-lang/coverage/blob/3719fbddadb07beac2529f0ceb4150d503475ee0/bin/collect_coverage.dart#L33)):</sup>
Debated back and forth on this one for a bit; I think I'm allergic to throw. But you're right, they're equivalent. And it's shorter and sweeter. Done.

---

<sup>**[bin/collect_coverage.dart, line 55 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/78#-Jpx4IuhmekKND7aOQZc)** ([raw file](https://github.com/dart-lang/coverage/blob/3719fbddadb07beac2529f0ceb4150d503475ee0/bin/collect_coverage.dart#L55)):</sup>
Not a problem since onTimeout() includes an exit(), but will do it for the principle of the matter. ;)

---

<sup>**[bin/collect_coverage.dart, line 70 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/78#-Jpx4hColgOBtmXubtnJ)** ([raw file](https://github.com/dart-lang/coverage/blob/3719fbddadb07beac2529f0ceb4150d503475ee0/bin/collect_coverage.dart#L70)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/78)

**Comment by kevmoo** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- bin/collect_coverage.dart @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/78)

**Pull request merged**
