### PR TITLE
#31 add support for `pub global run`

### PR DESCRIPTION
**Pull request by zoechi**

### CODE REVIEW

**Comment by devoncarew** [comment]
@cbracken

**Comment by cbracken** [comment]
lgtm

**Comment by seaneagan** [comment]
I'm a little late, but it seems like it would be better to namespace it to `dart` e.g. `dartcoverage format` `dartcoverage collect`.  `collect_coverage` is probably not likely to conflict, but it is unclear when you see it in a script what it does.

**Comment by cbracken** [comment]
@seaneagan There's work in progress to extract out a reasonable coverage API and replace both these scripts with something a bit more straightforward. I think that's excellent advice. Filed #58.

**Comment by devoncarew** [comment]
Hmm, what about prefixing with the package name? I think having the executable names namespaced by the package their contained in makes sense. So, in this case, something like `coverage_collect` and `coverage_format`.

**Comment by cbracken** [comment]
I believe what Sean is suggesting is that it would be useful to clarify in the name that this is a Dart-specific coverage tool and not C/Java/Intercal/etc.

**Comment by seaneagan** [comment]
@cbracken yes, that was my reason for wanting to prefix with `dart`.  I like `dartcov`  That might also make sense as the package name, similar to `dartdoc` and `dart_style`.  The `linter` was renamed from `dart_lint`, so it doesn't match that.

**Comment by cbracken** [comment]
I like `dartcov`; added a note to #58

**Pull request merged**
