### PR TITLE
Add support for "pub global activate"

### PR DESCRIPTION
**Pull request by johnryan-wf**
With this change, running "pub global activate" will add format_coverage and collect_coverage to PATH

### CODE REVIEW

**Comment by johnryan-wf** [comment]
@googlebot The CLA has been signed

**Comment by zoechi** [comment]
Looks like pull/54

**Comment by devoncarew** [comment]
@cbracken

**Comment by cbracken** [comment]
Thanks for this, #54 is now merged, which resolves the issue.

**Pull request closed without merging**
