### PR TITLE
Added support for checked mode in `runAndCollect` function

### LINKED ISSUE #143: Request: add support for checked mode in `runAndCollect` function
I usually run my tests in checked mode in order to catch every possible error in continuous integration.

My tests are based on the [`test`](https://pub.dartlang.org/packages/test) package, and their runner has the checked mode enabled by default (see files [`vm/platform.dart`](https://github.com/dart-lang/test/blob/master/lib/src/runner/vm/platform.dart#L53), [`runner/browser/content_shell.dart`](https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/content_shell.dart#L39) and [`runner/browser/dartium.dart`](https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/dartium.dart#L60)).

I'm developing a [Grinder](https://github.com/google/grinder.dart) plugin that collects the code coverage using the `runAndCollect` function, and I would like that my tests to have the same behavior with or without coverage.

So it would be cool if an optional `bool checked` parameter were added.

### PR DESCRIPTION
**Pull request by cedx**
Fixes #143

### CODE REVIEW

**Comment by cbracken** [comment]
lgtm

**Comment by cbracken** [comment]
Thank you very much! (et merci beaucoup!)

**Comment by cbracken** [comment]
Also -- feel free to send a PR to add yourself to the AUTHORS file if you like.

**Comment by cbracken** [comment]
Released in version [0.8.1](https://pub.dartlang.org/packages/coverage).

**Comment by cedx** [comment]
Thanks to you :)

**Pull request merged**
