### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by kevmoo**
Tests were failing with the latest SDK

I fixed that and updated our infrastructure to use vm_service_client

### CODE REVIEW

**Comment by kevmoo** [comment]
@cbracken This would be a good start on the migration :smile:

**Comment by evanweible-wf** [comment]
@kevmoo @cbracken any update on this? Would be great to have this fix!

**Comment by kevmoo** [comment]
I'll ask @cbracken to review after the fact so we can move forward. :smile:

**Comment by johnbland-wf** [comment]
@kevmoo how long do you think until this is tagged?

**Comment by kevmoo** [comment]
@johnbland-wf nowish :smile:

**Comment by johnbland-wf** [comment]
Yeah, saw that after commenting. lol. :) Still fails for me, but I'll double check some other things here first.

**Pull request merged**
