### PR TITLE
Remove packageRoot in run_and_collect

### PR DESCRIPTION
**Pull request by lukaslihotzki**
`--package-root=` is discontinued in dart.
(https://github.com/dart-lang/sdk/issues/41197)

### CODE REVIEW

**Comment by lukaslihotzki** [comment]
@googlebot I signed it!

**Comment by lukaslihotzki** [comment]
@googlebot I signed it!

**Comment by cbracken** [comment]
Thanks for your PR @lukaslihotzki! We'll also want to remove this from `bin/format_coverage.dart` and `lib/resolver.dart`. Would you mind ripping those out while you're at it?

**Review by cbracken — APPROVED** [review]
LGTM for the changes so far, just one minor request to kill off --package-root for format_coverate and resolver if you'd like to add that. 

We can land without those changes if you're uncomfortable making them, since they're already deprecated/unused by us. Let me know, and I'm happy to make that change if you'd prefer.

**Comment by cbracken** [comment]
Re-LGTM! Thanks @lukaslihotzki! Looks like permissions have changed and I don't have merge rights, but @kevmoo might be able to do the honours!

**Review by kevmoo — CHANGES_REQUESTED** [review]
We should update the changelog, though – right?

**Comment by cbracken** [comment]
Yep, we can do that here or if not, I'm happy to do it in a separate PR that also does the version bump.

**Review by kevmoo — APPROVED** [review]

**Comment by cbracken** [comment]
#326 for the version bump and changelog.

**Pull request merged**
