### PR TITLE
Version 0.13.3

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by cbracken** [comment]
Includes #270 by @willdrach-wk.

@willdrach-wk would you like to be added to the [AUTHORS](https://github.com/dart-lang/coverage/blob/master/AUTHORS) file? If so, let me know what the line should look like.

**Comment by cbracken** [comment]
Note, looks like the most recent published version was 0.13.2, not 0.13.3. I've updated the version/changelog to publish as 0.13.3 instead.

**Comment by willdrach-wk** [comment]
@cbracken on the AUTHORS file, that would be great, you can put me down as:
`Will Drach <will.drach@gmail.com>`

**Comment by cbracken** [comment]
Done!

**Comment by cbracken** [comment]
Version 0.13.3 has now been published to Pub.

**Pull request merged**
