### PR TITLE
Add Achilleas Anagnostopoulos to authors

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by cbracken** [comment]
@achilleasa friendly ping - let me know whether or not you'd prefer to be added to the authors list. :)

**Comment by achilleasa** [comment]
@cbracken Sorry for the late reply! It seems the original GH notification got lost from my mailbox. Can you please use my current email (achilleas.imap.mbox@gmail.com) instead of the one in this PR? Thanks in advance!

**Comment by cbracken** [comment]
Done!

**Pull request merged**
