### PR TITLE
Migrate format_coverage to async-await.

### PR DESCRIPTION
**Pull request by cbracken**
Addresses #75 for format_coverage.dart

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/coverage/79)

### CODE REVIEW

**Comment by kevmoo** [comment]
LGTM w/ comments

---

Review status: 0 of 1 files reviewed, 4 unresolved discussions, some commit checks pending.

---

<sup>**[bin/format_coverage.dart, line 5 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx5h0tNpRr0J5RSEoo)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L5)):</sup>
now this is unused

---

<sup>**[bin/format_coverage.dart, line 29 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx4y718MW4MXkuIY6A)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L29)):</sup>
Use a stopwatch instead of DateTime. Is a bit cheaper.

---

<sup>**[bin/format_coverage.dart, line 46 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx56geBnb33kWJ8Het)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L46)):</sup>
I'm a big fan of putting a type of vars that aren't assigned immediately. You're call.

---

<sup>**[bin/format_coverage.dart, line 51 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx5S7yFOA1uvzucwj6)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L51)):</sup>
Do an `else` with a `assert(env.lcov);` since we don't support anything else – it has to be one of 'em, right?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/79)

**Comment by kevmoo** [comment]
Review status: all files reviewed, 4 unresolved discussions, some commit checks pending.
Reviewed files:
- bin/format_coverage.dart @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/79)

**Comment by cbracken** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[bin/format_coverage.dart, line 5 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx5h0tNpRr0J5RSEoo)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L5)):</sup>
Done.

---

<sup>**[bin/format_coverage.dart, line 29 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx4y718MW4MXkuIY6A)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L29)):</sup>
There's a followup patch with that so as not to conflate the two changes.

---

<sup>**[bin/format_coverage.dart, line 46 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx56geBnb33kWJ8Het)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L46)):</sup>
SGTM. Done.

---

<sup>**[bin/format_coverage.dart, line 51 \[r1\]](https://reviewable.io:443/reviews/dart-lang/coverage/79#-Jpx5S7yFOA1uvzucwj6)** ([raw file](https://github.com/dart-lang/coverage/blob/84c7720d2f6a25bb13a70c21906798e10a3d6806/bin/format_coverage.dart#L51)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/79)

**Comment by kevmoo** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- bin/format_coverage.dart @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/79)

**Pull request merged**
