### PR TITLE
Task36 single command

### PR DESCRIPTION
**Pull request by zoechi**
added a `--script` option to make collect_coverate run the script and collect coverage information in one command.

### CODE REVIEW

**Comment by zoechi** [comment]
This Contributor License issue comes up when GitHub recognizes me a zoechigist instead of zoechi. I assume I renamed my account in my early GitHub days. GitHub itself admits that it can't handle account renames well but I read that only years later.

**Comment by kevmoo** [comment]
@zoechi What's the status w/ this? Seems like part of it landed...

**Comment by kevmoo** [comment]
@zoechi can we close this?

**Comment by zoechi** [comment]
Sure. Any plans to implement it yourself? It's nice and seems to work fine.

**Comment by cbracken** [comment]
First bit is merged in a separate patch. The second bit (`--script`) I'll take a look at right now.

**Comment by zoechi** [comment]
Don't worry about my PR, just make it work with the least amount of time necessary :-)

**Comment by cbracken** [comment]
@zoechi I've got a first run at this here: https://github.com/cbracken/coverage/tree/single_command

This makes a best attempt at locating a package root for the specified script and computes coverage. I'll look at extracting a new script for this that combines the functionality of collect_coverage and format_coverage.

**Pull request closed without merging**
