### PR TITLE
Support the latest service API in 1.11-dev.3

### PR DESCRIPTION
**Pull request by kevmoo**
Along with a bunch of other cleanup

[Review on Reviewable](https://reviewable.io/reviews/dart-lang/coverage/89)

### CODE REVIEW

**Comment by kevmoo** [comment]
@cbracken please use https://reviewable.io/reviews/dart-lang/coverage/89 for the review :smile:

**Comment by kevmoo** [comment]
@cbracken Hold off on this – tracking down some failures

**Comment by kevmoo** [comment]
@cbracken Okay, all is green. I fixed a few things around error handling so hopefully the next time the protocol changes, it'll be easier to diagnose.

**Comment by cbracken** [comment]
Review status: 0 of 5 files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[lib/src/devtools.dart, line 30 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpSUToWkw6ckd7anjO)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L30)):</sup>
Better yet: file an issue.

---

<sup>**[lib/src/devtools.dart, line 52 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpStn09IYVvnLiaHqj)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L52)):</sup>
If you haven't already, can you file a bug to kill the fallback logic once 1.11.0 rolls to stable?

---

<sup>**[lib/src/devtools.dart, line 164 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpSFJIMtebNg03bQgX)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L164)):</sup>
Renamed to _Connection since this is now the only one.

---

<sup>**[lib/src/devtools.dart, line 267 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpTNxOvUaXdTRVIDOU)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L267)):</sup>
Similar, file an issue to kill this off once 1.11 goes stable.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/89)

**Comment by kevmoo** [comment]
I have a rebased pull request coming. PTAL

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- bin/collect_coverage.dart @ r3
- lib/src/devtools.dart @ r4
- pubspec.yaml @ r1
- test/collect_coverage_test.dart @ r1
- tool/travis.sh @ r1

---

<sup>**[lib/src/devtools.dart, line 30 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpSUToWkw6ckd7anjO)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L30)):</sup>
https://github.com/dart-lang/coverage/issues/90

---

<sup>**[lib/src/devtools.dart, line 164 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpSFJIMtebNg03bQgX)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L164)):</sup>
This was done in a later commit in the same pull request.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/89)

**Comment by kevmoo** [comment]
Review status: 4 of 5 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[lib/src/devtools.dart, line 168 \[r4\]](https://reviewable.io:443/reviews/dart-lang/coverage/89#-JqpSFJIMtebNg03bQgX)** ([raw file](https://github.com/dart-lang/coverage/blob/52436aa00593b14e0059498da419f65de992e303/lib/src/devtools.dart#L168)):</sup>
Not sure why this is showing up – but this is fixed. See https://github.com/dart-lang/coverage/pull/89/files#diff-933b7723820926d92828a411da565850R168

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/89)

**Comment by kevmoo** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- lib/src/devtools.dart @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/89)

**Comment by cbracken** [comment]
lgtm

**Comment by cbracken** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- bin/collect_coverage.dart @ r3
- lib/src/devtools.dart @ r5
- pubspec.yaml @ r1
- test/collect_coverage_test.dart @ r1
- tool/travis.sh @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dart-lang/coverage/89)

**Pull request merged**
