### PR TITLE
Testing createHitmap

### PR DESCRIPTION
**Pull request by kevmoo**
[Review on Reviewable](https://reviewable.io/reviews/dart-lang/coverage/74)

### CODE REVIEW

**Comment by kevmoo** [comment]
@cbracken PTAL once travis is green.

This also gave me a chance to do some cleanup in hitmap to ensure that isolate errors are reported and don't hang the app.

**Comment by kevmoo** [comment]
@cbracken Let's get this released. I'm hitting crashes w/ coveralls

**Comment by cbracken** [comment]
Will do once it's reviewed :)

**Comment by cbracken** [comment]
Other than a few minor nits, lgtm.

**Pull request merged**
